Uni 165: Scenarios for boat compatible
coveo-labs/traffic-generator pull request #47
Opened 2022-07-11 16:00 UTC by abanik519

- Created a scenario that selects a random boat from the "Boat (compatible with)" facet and selects a random product
- Updated 'CoveoSelectFacetValueByText.js' to account for collapsed facets
- Added a pagination probability into the input of 'CoveoClickResultAtRandom'

2022-07-11 19:40 UTC, jdevost requested changes

2022-07-11 19:40 UTC, jdevost commented on tests/Barca.Engineering.boat_compatible_products.spec.js
> +const ExtractedQueries = require("../input/data/barca-engineering-data/boats-list.json");
We shouldn't need a pre-filled list of values. 

I am expecting something more like: 
```javascript
SelectRandomValueInFacet(page, 'eng_boat'); // using facetid, field or title
```

So we could then reuse the same command for other facets like Power Output, Battery Type or Memory.
We wouldn't want to extract values for each of these facets.

2022-07-11 19:40 UTC, jdevost commented on tests/RandomVisit.Barca.Engineering.spec.js
>      await CoveoSelectFacetValueByText(page, query, facetSelection, 'category', 'barca-eng');
While at it, can you replace the use of parameter `demoSite` by using the `process.env.SELECTORS` ?

Now that we have a global variable, we don't need to pass around a parameter like `demoSite` in functions. 
So `demoSise === "barca-eng` can be replaced by `process.env.SELECTORS === 'BarcaEngineering' `

2022-07-12 20:14 UTC, pkuttappan requested changes

2022-07-12 20:14 UTC, pkuttappan commented on tests/RandomVisit.Barca.Engineering.spec.js
> +    await page.pause();
This should be removed or commented out

2022-07-12 20:28 UTC, abanik519 commented on input/data/barca-engineering-data/boats-list.json
> +  ]
No I forgot to delete it, good catch!

2022-07-13 13:24 UTC, jdevost commented on commands/CoveoSelectFacetValueByText.js
> +    res = await selectFacetValueRecursive(page, facetValue, facetName, breadcrumbPath, demoSite);
I am getting a failure on 'demoSite' not being defined. 

`demoSite` need to be clean up in this file.

2022-07-13 17:28 UTC, jdevost approved these changes

2022-07-13 21:25 UTC, merged